# Create a Channel that declares resources that can be deployed
# Channel can be a Namespace, Object Store Bucket, or Helm Repo
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: hello-world-ns-channel
  namespace: hello-world-source
  labels:
    purpose: hello-world-demo
    appname: hello-world-demo
spec:
  type: Namespace
  pathname: hello-world-source

