apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: hello-world-demo-prereq
  name: hello-world-prereq-subscription
  namespace: hello-world-project
spec:
  channel: hello-world-source/hello-world-ns-channel
  packageFilter:
    labelSelector:
      matchLabels:
        appname: hello-world-demo
        prereq: "yes"
  placement:
    placementRef:
      name: demo-placementrule
      kind: PlacementRule
  overrides:
    - clusterName: "/"
      clusterOverrides:
        - path: "metadata.namespace"
          value: hello-world
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: hello-world-app-prereq
  namespace: hello-world-project
spec:
  selector:
    matchExpressions:
      - key: purpose
        operator: In
        values:
          - hello-world-demo-prereq
  componentKinds:
    - group: app.ibm.com/v1alpha1
      kind: Subscription
